version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  commit-workflow:
    jobs:
      - cypress/run :
          command: npm config delete proxy && npm config set http_proxy=http://sunitakac:sysbyp@ss4@sbrproxy01.cpall.co.th:8080 && npx cypress run --record --key 8480db50-7215-419a-bf3d-ea79ce325abc