version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  commit-workflow:
    jobs:
      - cypress/run :
          command: export HTTP_PROXY="http://sunitakac:sysbyp@ss4@sbrproxy01.cpall.co.th:8080" /M && npx cypress run