version: 2.1
orbs:
  win: circleci/windows@2.3.0
  cypress: cypress-io/cypress@1
workflows:
  commit-workflow:
    jobs:
      build:
        executor: win/default
        - cypress/run :
          command: npm config rm proxy && npm config rm https-proxy && npm config set proxy http://username:password@proxyname:8080 && npm config set https-proxy http://username:password@proxyname:8080 && npx cypress run
            
            
            
            # export HTTP_PROXY=http://sunitakac:sysbyp@ss4@sbrproxy01.cpall.co.th:8080  && echo '======1=======' && env && echo '=======2======' && echo $HTTP_PROXY && echo '=======3======' && npx cypress run